// Programmatic SEO (pSEO) Automated Article Generation Engine for BleuStream
// Generates 10 high-ranking, keyword-dense articles daily from TMDB Trending Movies, TV Series & Anime

import { SEOArticle, SEO_ARTICLES } from '../data/seoArticles';
import {
  fetchTrending,
  fetchPopular,
  fetchTopRated,
  fetchAnime,
  fetchDetails,
  fetchTVDetails,
  getPosterUrl,
  getBackdropUrl,
} from './tmdb';
import { MediaItem } from '../types';

const STORAGE_KEY_ARTICLES = 'bleustream_pseo_articles_v1';
const STORAGE_KEY_LAST_DATE = 'bleustream_pseo_last_gen_date';
const STORAGE_KEY_SETTINGS = 'bleustream_pseo_settings_v1';

export interface PSEOSettings {
  autoGenerateDaily: boolean;
  targetKeywordsStrategy: 'aggressive' | 'balanced' | 'long_tail';
  articlesPerDay: number;
  includeMovies: boolean;
  includeSeries: boolean;
  includeAnime: boolean;
  minWordCount: number;
  lastGeneratedDate: string | null;
}

const DEFAULT_SETTINGS: PSEOSettings = {
  autoGenerateDaily: true,
  targetKeywordsStrategy: 'aggressive',
  articlesPerDay: 10,
  includeMovies: true,
  includeSeries: true,
  includeAnime: true,
  minWordCount: 950,
  lastGeneratedDate: null,
};

function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Generate unique search angles if a movie is re-targeted
const SEARCH_INTENT_ANGLES = [
  (t: string, y: string) => `watch-${t}-${y}-online-free-hd`,
  (t: string, y: string) => `where-to-stream-${t}-${y}-4k-ultra-hd`,
  (t: string, y: string) => `complete-streaming-guide-${t}-${y}-free`,
  (t: string, y: string) => `watch-${t}-reddit-mirrors-1080p`,
  (t: string, y: string) => `stream-${t}-full-movie-without-signup`,
];

function detectOrGenerateFranchiseWatchOrder(
  title: string,
  category: string,
  isTv: boolean,
  year: string,
  mediaId: number
) {
  const lower = title.toLowerCase();

  if (lower.includes('dragon ball')) {
    return {
      franchiseName: 'Dragon Ball Universal Watch Order',
      description: 'Follow Goku and the Z-Fighters chronologically across all canonical sagas.',
      order: [
        { step: 1, title: 'Dragon Ball (Childhood & World Martial Arts)', year: '1986', type: 'TV Series' as const },
        { step: 2, title: 'Dragon Ball Z (Saiyan to Buu Saga)', year: '1989', type: 'TV Series' as const },
        { step: 3, title: 'Dragon Ball Super (Beerus to Tournament of Power)', year: '2015', type: 'TV Series' as const },
        { step: 4, title: 'Dragon Ball Super: Broly', year: '2018', type: 'Movie' as const },
        { step: 5, title: 'Dragon Ball Super: Super Hero', year: '2022', type: 'Movie' as const },
        { step: 6, title: 'Dragon Ball Daima', year: '2024', type: 'TV Series' as const, highlight: true, mediaId }
      ]
    };
  }

  if (lower.includes('fate')) {
    return {
      franchiseName: 'Type-Moon Fate Series Chronological Watch Order',
      description: 'The definitive chronological order for the Holy Grail War timeline.',
      order: [
        { step: 1, title: 'Fate/Zero (The 4th Holy Grail War Prequel)', year: '2011', type: 'Prequel' as const },
        { step: 2, title: 'Fate/stay night: Unlimited Blade Works (Rin Route)', year: '2014', type: 'TV Series' as const },
        { step: 3, title: 'Fate/stay night: Heaven\'s Feel Trilogy (Sakura Route)', year: '2017', type: 'Movie' as const },
        { step: 4, title: 'Fate/Apocrypha (Alternate Timeline)', year: '2017', type: 'TV Series' as const },
        { step: 5, title: 'Fate/Grand Order: Absolute Demonic Front: Babylonia', year: '2019', type: 'TV Series' as const, highlight: true, mediaId }
      ]
    };
  }

  if (lower.includes('monogatari') || lower.includes('bakemonogatari')) {
    return {
      franchiseName: 'Monogatari Series Light Novel & Anime Watch Order',
      description: 'Nisio Isin and Studio Shaft\'s supernatural mystery order from origins to final season.',
      order: [
        { step: 1, title: 'Kizumonogatari I, II & III (Vampire Origins Prequel)', year: '2016', type: 'Prequel' as const },
        { step: 2, title: 'Bakemonogatari (First Season)', year: '2009', type: 'TV Series' as const },
        { step: 3, title: 'Nisemonogatari (Second Season)', year: '2012', type: 'TV Series' as const },
        { step: 4, title: 'Monogatari Series: Second Season', year: '2013', type: 'TV Series' as const },
        { step: 5, title: 'Owarimonogatari & Zoku Owarimonogatari', year: '2015', type: 'TV Series' as const, highlight: true, mediaId }
      ]
    };
  }

  if (lower.includes('attack on titan') || lower.includes('shingeki')) {
    return {
      franchiseName: 'Attack on Titan (Shingeki no Kyojin) Chronological Saga',
      description: 'Follow humanity’s fight from the fall of Wall Maria to the apocalyptic Rumbling.',
      order: [
        { step: 1, title: 'Attack on Titan: Season 1 (Fall of Shiganshina)', year: '2013', type: 'TV Series' as const },
        { step: 2, title: 'Attack on Titan: Season 2 (Clash of the Titans)', year: '2017', type: 'TV Series' as const },
        { step: 3, title: 'Attack on Titan: Season 3 (Return to Shiganshina)', year: '2018', type: 'TV Series' as const },
        { step: 4, title: 'Attack on Titan: The Final Season & The Rumbling', year: '2020-2023', type: 'TV Series' as const, highlight: true, mediaId }
      ]
    };
  }

  if (lower.includes('one piece')) {
    return {
      franchiseName: 'One Piece Epic Saga Watch Order',
      description: 'Eiichiro Oda\'s pirate adventure from East Blue to the Final Saga.',
      order: [
        { step: 1, title: 'East Blue & Alabasta Sagas (Grand Line Entry)', year: '1999', type: 'TV Series' as const },
        { step: 2, title: 'Enies Lobby & Marineford Summit War Saga', year: '2006', type: 'TV Series' as const },
        { step: 3, title: 'Dressrosa & Whole Cake Island Sagas', year: '2014', type: 'TV Series' as const },
        { step: 4, title: 'Wano Country Arc & Gear 5 Awakening', year: '2019', type: 'TV Series' as const },
        { step: 5, title: 'Egghead Island Arc (The Final Saga)', year: '2024', type: 'TV Series' as const, highlight: true, mediaId }
      ]
    };
  }

  if (isTv || category === 'TV Series Guides' || category === 'Anime Guides') {
    const yInt = parseInt(year) || 2024;
    return {
      franchiseName: `${title} Chronological Storyline`,
      description: `Structured binge-watching timeline for ${title} across key story arcs and seasons.`,
      order: [
        { step: 1, title: `${title}: Season 1 (Origins & Premiere Arc)`, year: String(yInt - 1), type: 'TV Series' as const },
        { step: 2, title: `${title}: Season 2 (Rising Stakes & Escalation)`, year: String(yInt), type: 'TV Series' as const, highlight: true, mediaId },
        { step: 3, title: `${title}: Season 3 & OVA Special`, year: String(yInt + 1), type: 'TV Series' as const }
      ]
    };
  }

  return undefined;
}

function synthesizeSpecsAndWarnings(category: string, isTv: boolean, year: string) {
  const isAnime = category === 'Anime Guides';

  const specs = {
    runtime: isTv ? '45-60m per episode' : '118 min feature',
    certification: isAnime ? 'TV-14 (Anime)' : (isTv ? 'TV-MA' : 'PG-13'),
    studio: isAnime ? 'MAPPA / ufotable / Toei Animation' : (isTv ? 'HBO / Warner Bros. / Netflix' : 'Universal Pictures / Warner Bros.'),
    audioSubStatus: 'Dolby 5.1 Surround / Multi-Sub: EN, FR, ES, AR, DE',
    releaseYear: year
  };

  const contentWarning = {
    level: (isAnime ? 'Moderate (PG-13)' : (isTv ? 'Mature 18+' : 'Moderate (PG-13)')) as 'Family Friendly' | 'Moderate (PG-13)' | 'Mature 18+',
    summary: isAnime 
      ? 'Contains animated action sequences, stylized fantasy combat, and thematic tension.'
      : 'Contains cinematic suspense, thematic drama, action sequences, and emotional tension.',
    tags: isAnime 
      ? ['Stylized Combat', 'Anime Sakuga', 'Multi-Audio Dub & Sub', 'Uncensored']
      : ['Cinematic Peril', 'Action Violence', 'Dolby 5.1 Mix', 'High-Octane Drama']
  };

  const streamingStatus = {
    hdMirrorsStatus: '7 Dedicated High-Speed Cloud CDN Mirrors Online & Verified',
    audioAvailable: 'English Stereo 5.1 & Multi-Language Subtitles',
    officialAvailability: 'BleuStream VIP Ultra HD: 100% Free / Zero Buffering',
    qualityBadge: '4K Ultra HD & 1080p HDR'
  };

  return { specs, contentWarning, streamingStatus };
}

function synthesizeArticleForMedia(
  media: MediaItem,
  category: 'Movie Guides' | 'TV Series Guides' | 'Anime Guides',
  existingSlugs: Set<string>
): SEOArticle {
  const isTv =
    category === 'TV Series Guides' ||
    category === 'Anime Guides' ||
    media.media_type === 'tv' ||
    !!media.first_air_date;
  const title = media.title || media.name || 'Trending Cinema Title';
  const year = (
    media.release_date ||
    media.first_air_date ||
    new Date().getFullYear().toString()
  ).slice(0, 4);
  const ratingScore = (media.vote_average || 8.6).toFixed(1);
  const voteCount = media.vote_count || 1420;
  const today = new Date().toISOString().split('T')[0];
  const cleanTitle = title.toLowerCase();

  // Find a unique slug using search angles
  let baseSlug = '';
  for (const angleFn of SEARCH_INTENT_ANGLES) {
    const candidate = generateSlug(angleFn(cleanTitle, year));
    if (!existingSlugs.has(candidate)) {
      baseSlug = candidate;
      break;
    }
  }
  if (!baseSlug) {
    baseSlug = generateSlug(
      `watch-${cleanTitle}-${year}-stream-guide-${Date.now().toString().slice(-4)}`
    );
  }

  const cleanOverview =
    media.overview ||
    `Experience ${title} (${year}) in stunning high-definition streaming on BleuStream with 0% buffering, multi-language subtitles, and surround audio.`;

  // Dynamic Keyword Matrix targeting 1,000,000 search intent traffic
  const keywords = [
    `watch ${cleanTitle} online free`,
    `${cleanTitle} full movie stream 1080p`,
    `${cleanTitle} ${year} free stream no signup`,
    `stream ${cleanTitle} ultra hd 4k`,
    `${cleanTitle} english subtitles audio mirrors`,
    `where to watch ${cleanTitle} reddit mirror`,
    `${cleanTitle} cast rating and review`,
    `watch ${cleanTitle} free without registration`,
    `stream ${cleanTitle} 4k hdr bleustream`,
    `${cleanTitle} mobile and smart tv playback`,
  ];

  if (category === 'Anime Guides') {
    keywords.push(
      `${cleanTitle} anime sub and dub free`,
      `${cleanTitle} complete episode streaming`,
      `${cleanTitle} uncensored high quality`
    );
  } else if (category === 'TV Series Guides') {
    keywords.push(
      `${cleanTitle} complete season episodes free`,
      `${cleanTitle} binge watch series in 1080p`,
      `${cleanTitle} episode recap and ending explained`
    );
  }

  const metaTitle = `Watch ${title} (${year}) Online Free in 1080p & 4K | BleuStream Cinema`;
  const metaDescription = `Stream ${title} (${year}) online for free in 1080p Full HD & 4K Ultra HD on BleuStream. Discover synopsis, cast breakdown, verified mirror servers, and instant playback with 0% buffering.`;

  // Deep Structured Article Sections with High Keyword Density & Internal Cross-Links
  const sections = [
    {
      heading: `The Cinematic Phenomenon: Why ${title} (${year}) is Dominating Worldwide Trends`,
      paragraphs: [
        `${title} (${year}) has rapidly emerged as one of the most streamed and talked-about releases of the year. Featuring an exceptional blend of storytelling, top-tier cinematography, and stellar performances, it has captured the attention of critics and moviegoers across the globe.`,
        `${cleanOverview}`,
        `With an impressive viewer approval score of ${ratingScore}/10 across ${voteCount.toLocaleString()} verified ratings, ${title} proves that cinematic craftsmanship and high-stakes drama continue to draw massive streaming audiences worldwide.`,
      ],
      bulletPoints: [
        `Title: ${title} (${year})`,
        `Format: ${isTv ? 'Complete TV Series' : 'Full-Length Feature Film'} in 1080p / 4K Ultra HD`,
        `Audience Rating: ${ratingScore}/10 (${voteCount.toLocaleString()} verified reviews)`,
        `Playback Availability: 7 high-speed cloud CDN mirrors with stereo surround audio and multi-subtitles`,
        `Platform: 100% Free on BleuStream with Anti-Popup Ad-Shield protection`,
      ],
    },
    {
      heading: `Plot Synopsis, Thematic Depth & Narrative Execution (Spoiler-Free)`,
      paragraphs: [
        `At its core, ${title} explores universal themes of ambition, survival, resilience, and unexpected alliances. What distinguishes this title from standard genre releases is its pacing—balancing pulse-pounding sequences with character-driven moments that keep the audience emotionally invested from the opening frame to the final credits.`,
        `The creative vision behind ${title} shines through its meticulous attention to detail. Every set piece, musical cue, and camera angle serves to heighten tension, making it an essential title to add to your personal watchlist on BleuStream.`,
      ],
      bulletPoints: [
        `Visual Direction: Pristine color grading optimized for OLED & HDR screens`,
        `Pacing: Seamless balance between high-octane spectacle and character development`,
        `Critical Acclaim: Universally praised for writing, editing, and sound design`,
      ],
    },
    {
      heading: `BleuStream vs Traditional Subscriptions: The Free 4K Advantage`,
      paragraphs: [
        `While legacy subscription services continue raising prices and implementing strict account sharing restrictions, BleuStream provides a next-generation streaming alternative without monthly fees or credit card requirements.`,
        `Our decentralized streaming infrastructure aggregates the highest-speed cloud nodes (VidSrc Prime, Cloud CDN, and VIP Mirror) ensuring you never experience server overload or dead links during peak streaming hours.`,
      ],
      bulletPoints: [
        `No Monthly Subscription: 100% Free ($0 vs $19.99/mo for standard streaming plans)`,
        `No Account Creation Required: Start streaming immediately with zero registration`,
        `Adaptive Bitrate: Automatic bandwidth scaling from 720p to 1080p Full HD & 4K Ultra HD`,
        `Multi-Language Subtitles: English, French, Spanish, German, and Arabic supported`,
      ],
    },
    {
      heading: `Technical Breakdown: Multi-Mirror CDN Architecture & Anti-Buffering`,
      paragraphs: [
        `Streaming full-length cinema titles online is often ruined by intrusive pop-up advertisements, slow bandwidth buffering, and broken video links. BleuStream was engineered from the ground up to solve these exact frustrations.`,
        `When you stream ${title} on BleuStream, you gain access to our distributed cloud CDN network. Our multi-mirror architecture automatically connects you to the fastest server in your region, guaranteeing instant seek response and zero lag.`,
      ],
      bulletPoints: [
        `0% Buffering: High-throughput cloud streaming mirrors (VidSrc Prime, Cloud, and VIP)`,
        `Anti-Ad Shield: Built-in sandbox filter that suppresses rogue popups and unwanted redirects`,
        `Cross-Device Compatibility: Responsive cinema player optimized for smartphones, tablets, and 4K smart TVs`,
        `Audio Quality: Crystal-clear Dolby Stereo 5.1 surround mix for an immersive theater experience`,
      ],
    },
    {
      heading: `Step-by-Step Guide: How to Start Watching ${title} Right Now`,
      paragraphs: [
        `Getting started takes less than 5 seconds: Click the large red Watch button at the top of this guide or launch our Ultra HD Cinema Player. You can switch between audio languages and subtitles using the in-player controls.`,
        `If your internet connection fluctuates, you can seamlessly switch between VidSrc Server 1, Server 2, or Server 3 using the floating toolbar directly above the stream container.`,
      ],
      bulletPoints: [
        `Step 1: Click the red 'Watch Free Now' button below`,
        `Step 2: Choose your preferred audio track and subtitle language`,
        `Step 3: Toggle full-screen mode and enjoy uninterrupted cinema streaming`,
      ],
    },
  ];

  // Schema.org FAQ Rich Snippet Accordion
  const faqs = [
    {
      question: `Is ${title} available to watch for free on BleuStream?`,
      answer: `Yes, ${title} (${year}) is available to stream completely free in 1080p Full HD and 4K Ultra HD on BleuStream without any subscription or sign-up required.`,
    },
    {
      question: `Are English subtitles and multi-language audio tracks included?`,
      answer: `Yes, all our high-speed VidSrc mirrors feature multi-language subtitles including English, Spanish, French, and Arabic, alongside crystal-clear surround audio.`,
    },
    {
      question: `What should I do if the video buffers or fails to load?`,
      answer: `Simply click the 'Next Server' button or switch between VidSrc 1, VidSrc 2, and VidSrc 3 in the streaming server selector above the video player.`,
    },
    {
      question: `Can I stream ${title} on mobile devices (iPhone and Android)?`,
      answer: `Yes, BleuStream is fully responsive and optimized for mobile browsers with full-screen playback, touch gesture controls, and low data mode.`,
    },
  ];

  const coverImage =
    getBackdropUrl(media.backdrop_path) || getPosterUrl(media.poster_path);

  const { specs, contentWarning, streamingStatus } = synthesizeSpecsAndWarnings(category, isTv, year);
  const franchiseWatchOrder = detectOrGenerateFranchiseWatchOrder(title, category, isTv, year, media.id);

  const similarTitles = [
    { id: 693134, title: 'Dune: Part Two', mediaType: 'movie' as const, rating: '8.6/10', year: '2024', slug: 'how-to-watch-dune-part-two-online-free-hd' },
    { id: 157336, title: 'Interstellar', mediaType: 'movie' as const, rating: '8.7/10', year: '2014', slug: 'interstellar-movie-streaming-review-cast' },
    { id: 85937, title: 'Demon Slayer', mediaType: 'tv' as const, rating: '8.6/10', year: '2024', slug: 'demon-slayer-infinity-castle-movie-guide' },
    { id: 127532, title: 'Solo Leveling', mediaType: 'tv' as const, rating: '8.4/10', year: '2024', slug: 'solo-leveling-anime-watch-guide-season-2' },
  ].filter((s) => s.id !== media.id);

  return {
    id: `pseo-${media.id}-${baseSlug}`,
    slug: baseSlug,
    title: `${title} (${year}) – Complete Streaming Guide & Where to Watch Free in HD`,
    metaTitle,
    metaDescription,
    category,
    publishedDate: today,
    modifiedDate: today,
    readTime: '8 min read',
    author: 'BleuStream Cinema Editorial',
    authorRole: 'Chief Streaming Analyst & Film Critic',
    coverImage,
    rating: `${ratingScore}/10 IMDb`,
    relatedMediaId: media.id,
    relatedMediaType: isTv ? 'tv' : 'movie',
    relatedMediaTitle: title,
    keywords,
    excerpt: `Everything you need to know about streaming ${title} (${year}) in Ultra HD 1080p and 4K with multiple audio mirrors, complete episode list, and verified subtitles on BleuStream.`,
    sections,
    faqs,
    director: isTv ? 'Lead Series Director & Creator' : 'Principal Feature Film Director',
    topActors: ['Principal Lead Actor', 'Co-Starring Ensemble', 'Supporting Cast'],
    specs,
    contentWarning,
    streamingStatus,
    franchiseWatchOrder,
    similarTitles,
  };
}

class PSEOEngineService {
  private customArticles: SEOArticle[] = [];
  private settings: PSEOSettings = DEFAULT_SETTINGS;
  private isGenerating = false;
  private listeners: Array<() => void> = [];

  public getArticleByMediaId(mediaId: number): SEOArticle | undefined {
    return this.getAllArticles().find((a) => a.relatedMediaId === mediaId);
  }

  public getOrCreateArticleForMedia(
    media: MediaItem,
    category?: 'Movie Guides' | 'TV Series Guides' | 'Anime Guides'
  ): SEOArticle {
    const all = this.getAllArticles();
    const existing = all.find(
      (a) =>
        (media.id && a.relatedMediaId === media.id) ||
        (media.title && a.relatedMediaTitle.toLowerCase() === media.title.toLowerCase()) ||
        (media.name && a.relatedMediaTitle.toLowerCase() === media.name.toLowerCase())
    );
    if (existing) return existing;

    const cat: 'Movie Guides' | 'TV Series Guides' | 'Anime Guides' =
      category ||
      (media.genre_ids?.includes(16)
        ? 'Anime Guides'
        : media.media_type === 'tv' || media.first_air_date
        ? 'TV Series Guides'
        : 'Movie Guides');

    const existingSlugs = new Set(all.map((a) => a.slug));
    const newArt = synthesizeArticleForMedia(media, cat, existingSlugs);
    this.customArticles.unshift(newArt);
    this.saveState();
    return newArt;
  }

  public async getOrCreateArticleByMediaId(
    mediaId: number,
    mediaType: 'movie' | 'tv' = 'movie',
    title?: string
  ): Promise<SEOArticle> {
    const all = this.getAllArticles();
    const existing = all.find(
      (a) =>
        (mediaId && a.relatedMediaId === mediaId) ||
        (title && a.relatedMediaTitle.toLowerCase() === title.toLowerCase())
    );
    if (existing) return existing;

    try {
      const details =
        mediaType === 'tv'
          ? await fetchTVDetails(mediaId)
          : await fetchDetails(mediaType, mediaId);
      if (details) {
        return this.getOrCreateArticleForMedia(details);
      }
    } catch {
      // ignore
    }

    const fallbackItem: MediaItem = {
      id: mediaId,
      title: title || 'Cinema Title',
      name: title || 'Cinema Title',
      overview: `Stream ${title || 'this title'} in pristine 1080p and 4K Ultra HD on BleuStream with 0% buffering, multi-language subtitles, and surround audio.`,
      poster_path: '',
      backdrop_path: '',
      vote_average: 8.5,
      vote_count: 1420,
      media_type: mediaType,
    };
    return this.getOrCreateArticleForMedia(fallbackItem);
  }

  constructor() {
    this.loadState();
    // Run automated check if today's articles are generated
    if (typeof window !== 'undefined') {
      setTimeout(() => {
        this.checkAndAutoGenerate();
      }, 2500);

      // Background periodic check every 15 minutes to guarantee daily automated generation
      setInterval(() => {
        this.checkAndAutoGenerate();
      }, 15 * 60 * 1000);
    }
  }

  private loadState() {
    if (typeof window === 'undefined') return;

    try {
      const savedArticles = localStorage.getItem(STORAGE_KEY_ARTICLES);
      if (savedArticles) {
        this.customArticles = JSON.parse(savedArticles);
      }

      const savedSettings = localStorage.getItem(STORAGE_KEY_SETTINGS);
      if (savedSettings) {
        this.settings = { ...DEFAULT_SETTINGS, ...JSON.parse(savedSettings) };
      }

      const lastDate = localStorage.getItem(STORAGE_KEY_LAST_DATE);
      if (lastDate) {
        this.settings.lastGeneratedDate = lastDate;
      }
    } catch (e) {
      console.warn('Error loading pSEO state:', e);
    }
  }

  private saveState() {
    if (typeof window === 'undefined') return;
    try {
      localStorage.setItem(STORAGE_KEY_ARTICLES, JSON.stringify(this.customArticles));
      localStorage.setItem(STORAGE_KEY_SETTINGS, JSON.stringify(this.settings));
      if (this.settings.lastGeneratedDate) {
        localStorage.setItem(STORAGE_KEY_LAST_DATE, this.settings.lastGeneratedDate);
      }
    } catch (e) {
      console.warn('Error saving pSEO state:', e);
    }
    this.notify();
  }

  private notify() {
    this.listeners.forEach((cb) => {
      try {
        cb();
      } catch {
        // ignore
      }
    });
  }

  public subscribe(cb: () => void): () => void {
    this.listeners.push(cb);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== cb);
    };
  }

  public getAllArticles(): SEOArticle[] {
    // Return custom generated articles first, followed by baseline curated articles
    const map = new Map<string, SEOArticle>();

    // Add baseline curated articles
    SEO_ARTICLES.forEach((a) => map.set(a.slug, a));

    // Override or append dynamically generated articles
    this.customArticles.forEach((a) => map.set(a.slug, a));

    return Array.from(map.values()).sort((a, b) => {
      return (b.publishedDate || '').localeCompare(a.publishedDate || '');
    });
  }

  public getGeneratedArticles(): SEOArticle[] {
    return [...this.customArticles];
  }

  public getSettings(): PSEOSettings {
    return { ...this.settings };
  }

  public updateSettings(partial: Partial<PSEOSettings>): PSEOSettings {
    this.settings = { ...this.settings, ...partial };
    this.saveState();
    return this.getSettings();
  }

  public async checkAndAutoGenerate(): Promise<boolean> {
    if (!this.settings.autoGenerateDaily) return false;

    const today = new Date().toISOString().split('T')[0];
    // Check how many custom articles were generated today
    const generatedToday = this.customArticles.filter(
      (a) => a.publishedDate === today
    ).length;

    if (generatedToday >= 10 && this.settings.lastGeneratedDate === today) {
      return false; // Already reached daily 10 articles quota
    }

    try {
      const added = await this.generateDailyTrendingArticles(false);
      return added.length > 0;
    } catch (err) {
      console.warn('Automated pSEO generation check error:', err);
      return false;
    }
  }

  // Generates 10 top trending articles GUARANTEED (4 movies, 3 tv series, 3 anime)
  public async generateDailyTrendingArticles(force = true): Promise<SEOArticle[]> {
    if (this.isGenerating) return [];
    this.isGenerating = true;

    try {
      const today = new Date().toISOString().split('T')[0];
      const existingSlugs = new Set(this.getAllArticles().map((a) => a.slug));
      const existingMediaIds = new Set(
        this.customArticles.map((a) => a.relatedMediaId)
      );

      // 1. Fetch extensive media pools from TMDB
      const [
        trendingMovies,
        popularMovies,
        topRatedMovies,
        trendingTv,
        popularTv,
        animeP1,
        animeP2,
      ] = await Promise.all([
        fetchTrending('movie', 'day').catch(() => []),
        fetchPopular('movie', 1).catch(() => []),
        fetchTopRated('movie', 1).catch(() => []),
        fetchTrending('tv', 'day').catch(() => []),
        fetchPopular('tv', 1).catch(() => []),
        fetchAnime('all', 1).catch(() => []),
        fetchAnime('all', 2).catch(() => []),
      ]);

      // Combine and deduplicate candidates
      const allMovieCandidates: MediaItem[] = [
        ...trendingMovies,
        ...popularMovies,
        ...topRatedMovies,
      ];
      const allTvCandidates: MediaItem[] = [...trendingTv, ...popularTv];
      const allAnimeCandidates: MediaItem[] = [...animeP1, ...animeP2];

      const newArticles: SEOArticle[] = [];

      // A. Pick 4 Unseen Movies (or fallback with fresh search angle)
      let selectedMovies: MediaItem[] = allMovieCandidates.filter(
        (m) => !existingMediaIds.has(m.id)
      );
      if (selectedMovies.length < 4) {
        selectedMovies = allMovieCandidates; // Reuse with distinct angle
      }
      for (const movie of selectedMovies) {
        if (newArticles.filter((a) => a.category === 'Movie Guides').length >= 4) break;
        const art = synthesizeArticleForMedia(movie, 'Movie Guides', existingSlugs);
        existingSlugs.add(art.slug);
        existingMediaIds.add(movie.id);
        newArticles.push(art);
      }

      // B. Pick 3 Unseen TV Series
      let selectedTv: MediaItem[] = allTvCandidates.filter(
        (t) => !existingMediaIds.has(t.id)
      );
      if (selectedTv.length < 3) {
        selectedTv = allTvCandidates;
      }
      for (const tv of selectedTv) {
        if (newArticles.filter((a) => a.category === 'TV Series Guides').length >= 3) break;
        const art = synthesizeArticleForMedia(tv, 'TV Series Guides', existingSlugs);
        existingSlugs.add(art.slug);
        existingMediaIds.add(tv.id);
        newArticles.push(art);
      }

      // C. Pick 3 Unseen Anime
      let selectedAnime: MediaItem[] = allAnimeCandidates.filter(
        (a) => !existingMediaIds.has(a.id)
      );
      if (selectedAnime.length < 3) {
        selectedAnime = allAnimeCandidates;
      }
      for (const anime of selectedAnime) {
        if (newArticles.filter((a) => a.category === 'Anime Guides').length >= 3) break;
        const art = synthesizeArticleForMedia(anime, 'Anime Guides', existingSlugs);
        existingSlugs.add(art.slug);
        existingMediaIds.add(anime.id);
        newArticles.push(art);
      }

      if (newArticles.length === 0) {
        throw new Error('Could not synthesize articles from available catalog.');
      }

      // Prepend all new articles to customArticles
      newArticles.forEach((art) => {
        this.customArticles.unshift(art);
      });

      this.settings.lastGeneratedDate = today;
      this.saveState();
      return newArticles;
    } finally {
      this.isGenerating = false;
    }
  }

  public deleteArticle(idOrSlug: string): boolean {
    const beforeCount = this.customArticles.length;
    this.customArticles = this.customArticles.filter(
      (a) => a.id !== idOrSlug && a.slug !== idOrSlug
    );
    if (this.customArticles.length !== beforeCount) {
      this.saveState();
      return true;
    }
    return false;
  }

  public clearGeneratedArticles(): void {
    this.customArticles = [];
    this.settings.lastGeneratedDate = null;
    this.saveState();
  }

  public getStats() {
    const all = this.getAllArticles();
    const generated = this.customArticles;
    const today = new Date().toISOString().split('T')[0];

    const totalKeywords = all.reduce((sum, a) => sum + (a.keywords?.length || 0), 0);

    const categoriesCount = {
      movies: all.filter((a) => a.category === 'Movie Guides').length,
      series: all.filter((a) => a.category === 'TV Series Guides').length,
      anime: all.filter((a) => a.category === 'Anime Guides').length,
      curated: all.filter((a) => a.category === 'Curated Recommendations').length,
    };

    return {
      totalArticles: all.length,
      generatedCount: generated.length,
      curatedCount: SEO_ARTICLES.length,
      totalKeywordsTargeted: totalKeywords,
      lastGeneratedDate: this.settings.lastGeneratedDate,
      isGeneratedToday: this.settings.lastGeneratedDate === today,
      categoriesCount,
      estimatedMonthlySearchImpressions: all.length * 45000,
    };
  }
}

export const pseoEngine = new PSEOEngineService();
