// Programmatic SEO (pSEO) Automated Article Generation Engine for BleuStream
// Generates 10 high-ranking, keyword-dense articles daily from TMDB Trending Movies, TV Series & Anime

import { SEOArticle, SEO_ARTICLES } from '../data/seoArticles';
import { fetchTrending, fetchAnime, getPosterUrl, getBackdropUrl } from './tmdb';
import { MediaItem } from '../types';

const STORAGE_KEY_ARTICLES = 'bleustream_pseo_articles_v1';
const STORAGE_KEY_LAST_DATE = 'bleustream_pseo_last_gen_date';
const STORAGE_KEY_SETTINGS = 'bleustream_pseo_settings_v1';

export interface PSEOSettings {
  autoGenerateDaily: boolean;
  targetKeywordsStrategy: 'aggressive' | 'balanced' | 'long_tail';
  articlesPerDay: number;
  includeMovies: boolean;
  includeSeries: boolean;
  includeAnime: boolean;
  minWordCount: number;
  lastGeneratedDate: string | null;
}

const DEFAULT_SETTINGS: PSEOSettings = {
  autoGenerateDaily: true,
  targetKeywordsStrategy: 'aggressive',
  articlesPerDay: 10,
  includeMovies: true,
  includeSeries: true,
  includeAnime: true,
  minWordCount: 850,
  lastGeneratedDate: null,
};

// Power keywords vocabulary for cinema search intent
const SEARCH_INTENT_PREFIXES = [
  'How to Watch',
  'Where to Stream',
  'Full Movie Free Stream Guide:',
  'Watch Online Free 1080p:',
  'Complete Series Streaming Guide:',
  'HD Cinema Review & Stream Guide:',
];

function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function synthesizeArticleForMedia(media: MediaItem, category: 'Movie Guides' | 'TV Series Guides' | 'Anime Guides'): SEOArticle {
  const isTv = category === 'TV Series Guides' || category === 'Anime Guides' || media.media_type === 'tv' || !!media.first_air_date;
  const title = media.title || media.name || 'Trending Title';
  const year = (media.release_date || media.first_air_date || new Date().getFullYear().toString()).slice(0, 4);
  const ratingScore = (media.vote_average || 8.5).toFixed(1);
  const voteCount = media.vote_count || 1250;
  const today = new Date().toISOString().split('T')[0];

  const slug = generateSlug(`watch-${title}-${year}-online-free-hd`);
  const cleanOverview = media.overview || `Experience ${title} (${year}) in stunning high-definition streaming on BleuStream.`;

  // Dynamic Keyword Generator for High-Volume Search Intent
  const cleanTitle = title.toLowerCase();
  const keywords = [
    `watch ${cleanTitle} online free`,
    `${cleanTitle} full movie stream 1080p`,
    `${cleanTitle} ${year} free stream no signup`,
    `stream ${cleanTitle} ultra hd 4k`,
    `${cleanTitle} english subtitles audio mirrors`,
    `where to watch ${cleanTitle} reddit mirror`,
    `${cleanTitle} cast rating and review`,
  ];

  if (category === 'Anime Guides') {
    keywords.push(`${cleanTitle} anime sub and dub`, `${cleanTitle} episode stream online free`);
  } else if (category === 'TV Series Guides') {
    keywords.push(`${cleanTitle} complete season episodes free`, `${cleanTitle} tv show watch free`);
  }

  const metaTitle = `Watch ${title} (${year}) Online Free in 1080p & 4K | BleuStream Cinema`;
  const metaDescription = `Stream ${title} (${year}) online for free in 1080p Full HD & 4K Ultra HD on BleuStream. Discover synopsis, cast breakdown, verified mirror servers, and instant playback with 0% buffering.`;

  // Deep Structured Article Sections with High Keyword Density
  const sections = [
    {
      heading: `The Cinematic Phenomenon: Why ${title} (${year}) is Dominating Worldwide Trends`,
      paragraphs: [
        `${title} (${year}) has rapidly emerged as one of the most streamed and talked-about releases of the year. Featuring an exceptional blend of storytelling, top-tier cinematography, and stellar performances, it has captured the attention of critics and moviegoers across the globe.`,
        `${cleanOverview}`,
        `With an impressive viewer approval score of ${ratingScore}/10 across thousands of verified reviews, ${title} proves that cinematic craftsmanship and high-stakes drama continue to draw massive streaming audiences.`
      ],
      bulletPoints: [
        `Title: ${title} (${year})`,
        `Format: ${isTv ? 'Complete TV Series' : 'Full-Length Feature Film'} in 1080p / 4K Ultra HD`,
        `Audience Rating: ${ratingScore}/10 (${voteCount.toLocaleString()} verified ratings)`,
        `Playback Availability: 7 high-speed CDN mirrors with stereo surround audio and multi-subtitles`,
        `Platform: 100% Free on BleuStream with Anti-Popup Ad-Shield protection`
      ]
    },
    {
      heading: `Plot Synopsis & Thematic Depth`,
      paragraphs: [
        `At its core, ${title} explores universal themes of ambition, survival, and unexpected alliances. What distinguishes this title from standard genre releases is its pacing—balancing pulse-pounding sequences with character-driven moments that keep the audience emotionally invested from the opening frame to the final credits.`,
        `The creative vision behind ${title} shines through its attention to detail. Every set piece, musical cue, and camera angle serves to heighten tension and deliver a truly memorable cinema experience.`
      ]
    },
    {
      heading: `Why Stream ${title} on BleuStream? Ultra HD Mirrors & Anti-Buffering Architecture`,
      paragraphs: [
        `Streaming full-length titles online is often ruined by intrusive pop-up advertisements, slow bandwidth buffering, and broken video links. BleuStream was engineered from the ground up to solve these exact frustrations.`,
        `When you stream ${title} on BleuStream, you gain access to our distributed VidSrc cloud CDN network. Our multi-mirror architecture automatically connects you to the fastest server in your region, guaranteeing 1080p and 4K playback with instant seek response and zero lag.`
      ],
      bulletPoints: [
        `0% Buffering: High-throughput cloud streaming mirrors (VidSrc Prime, Cloud, and VIP)`,
        `Multi-Audio & Subtitles: Built-in tracks for English, Spanish, French, German, and Arabic`,
        `Anti-Ad Shield: Built-in sandbox filter that suppresses rogue popups and unwanted redirects`,
        `Multi-Device Ready: Responsive cinema player optimized for smartphones, tablets, and 4K smart TVs`
      ]
    },
    {
      heading: `Step-by-Step Guide: How to Start Watching ${title} Right Now`,
      paragraphs: [
        `Getting started takes less than 5 seconds: Click the large red/blue Play button above to launch our Ultra HD Cinema Player. You can switch between audio languages and subtitles using the in-player controls.`,
        `If your internet connection fluctuates, you can seamlessly switch between VidSrc Server 1, Server 2, or Server 3 using the floating toolbar directly above the stream container.`
      ]
    }
  ];

  // Schema.org FAQ Rich Snippet Accordion
  const faqs = [
    {
      question: `Is ${title} available to watch for free on BleuStream?`,
      answer: `Yes, ${title} (${year}) is available to stream completely free in 1080p Full HD and 4K Ultra HD on BleuStream without any subscription or sign-up required.`
    },
    {
      question: `Are English subtitles and multi-language audio tracks included?`,
      answer: `Yes, all our high-speed VidSrc mirrors feature multi-language subtitles including English, Spanish, French, and Arabic, alongside crystal-clear surround audio.`
    },
    {
      question: `What should I do if the video buffers or fails to load?`,
      answer: `Simply click the 'Next Server' button or switch between VidSrc 1, VidSrc 2, and VidSrc 3 in the streaming server selector above the video player.`
    },
    {
      question: `Can I stream ${title} on mobile devices (iPhone and Android)?`,
      answer: `Yes, BleuStream is fully responsive and optimized for mobile browsers with full-screen playback and touch gesture controls.`
    }
  ];

  const coverImage = getBackdropUrl(media.backdrop_path) || getPosterUrl(media.poster_path);

  return {
    id: `pseo-${media.id}-${today}`,
    slug,
    title: `${title} (${year}) – Complete Streaming Guide & Where to Watch Free in HD`,
    metaTitle,
    metaDescription,
    category,
    publishedDate: today,
    modifiedDate: today,
    readTime: '7 min read',
    author: 'BleuStream Cinema Editorial',
    authorRole: 'Chief Streaming Analyst & Film Critic',
    coverImage,
    rating: `${ratingScore}/10 IMDb`,
    relatedMediaId: media.id,
    relatedMediaType: isTv ? 'tv' : 'movie',
    relatedMediaTitle: title,
    keywords,
    excerpt: `Everything you need to know about streaming ${title} (${year}) in Ultra HD 1080p and 4K with multiple audio mirrors, complete episode list, and verified subtitles on BleuStream.`,
    sections,
    faqs,
  };
}

class PSEOEngineService {
  private customArticles: SEOArticle[] = [];
  private settings: PSEOSettings = DEFAULT_SETTINGS;
  private isGenerating = false;
  private listeners: Array<() => void> = [];

  constructor() {
    this.loadState();
    // Run automated check if today's articles are generated
    if (typeof window !== 'undefined') {
      setTimeout(() => {
        this.checkAndAutoGenerate();
      }, 3000);
    }
  }

  private loadState() {
    if (typeof window === 'undefined') return;

    try {
      const savedArticles = localStorage.getItem(STORAGE_KEY_ARTICLES);
      if (savedArticles) {
        this.customArticles = JSON.parse(savedArticles);
      }

      const savedSettings = localStorage.getItem(STORAGE_KEY_SETTINGS);
      if (savedSettings) {
        this.settings = { ...DEFAULT_SETTINGS, ...JSON.parse(savedSettings) };
      }

      const lastDate = localStorage.getItem(STORAGE_KEY_LAST_DATE);
      if (lastDate) {
        this.settings.lastGeneratedDate = lastDate;
      }
    } catch (e) {
      console.warn('Error loading pSEO state:', e);
    }
  }

  private saveState() {
    if (typeof window === 'undefined') return;
    try {
      localStorage.setItem(STORAGE_KEY_ARTICLES, JSON.stringify(this.customArticles));
      localStorage.setItem(STORAGE_KEY_SETTINGS, JSON.stringify(this.settings));
      if (this.settings.lastGeneratedDate) {
        localStorage.setItem(STORAGE_KEY_LAST_DATE, this.settings.lastGeneratedDate);
      }
    } catch (e) {
      console.warn('Error saving pSEO state:', e);
    }
    this.notify();
  }

  private notify() {
    this.listeners.forEach((cb) => {
      try {
        cb();
      } catch {
        // ignore
      }
    });
  }

  public subscribe(cb: () => void): () => void {
    this.listeners.push(cb);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== cb);
    };
  }

  public getAllArticles(): SEOArticle[] {
    // Return custom generated articles first, followed by baseline curated articles
    const map = new Map<string, SEOArticle>();

    // Add baseline curated articles
    SEO_ARTICLES.forEach((a) => map.set(a.slug, a));

    // Override or append dynamically generated articles
    this.customArticles.forEach((a) => map.set(a.slug, a));

    return Array.from(map.values()).sort((a, b) => {
      return (b.publishedDate || '').localeCompare(a.publishedDate || '');
    });
  }

  public getGeneratedArticles(): SEOArticle[] {
    return [...this.customArticles];
  }

  public getSettings(): PSEOSettings {
    return { ...this.settings };
  }

  public updateSettings(partial: Partial<PSEOSettings>): PSEOSettings {
    this.settings = { ...this.settings, ...partial };
    this.saveState();
    return this.getSettings();
  }

  public async checkAndAutoGenerate(): Promise<boolean> {
    if (!this.settings.autoGenerateDaily) return false;

    const today = new Date().toISOString().split('T')[0];
    if (this.settings.lastGeneratedDate === today && this.customArticles.length >= 10) {
      return false; // Already generated for today
    }

    try {
      await this.generateDailyTrendingArticles(false);
      return true;
    } catch (err) {
      console.warn('Automated pSEO generation check error:', err);
      return false;
    }
  }

  // Generates 10 top trending articles (4 movies, 3 tv series, 3 anime)
  public async generateDailyTrendingArticles(force = true): Promise<SEOArticle[]> {
    if (this.isGenerating) return [];
    this.isGenerating = true;

    try {
      const today = new Date().toISOString().split('T')[0];

      // 1. Fetch trending movies, tv series, and anime from TMDB API
      const [moviesRes, tvRes, animeRes] = await Promise.all([
        fetchTrending('movie', 'day').catch(() => []),
        fetchTrending('tv', 'day').catch(() => []),
        fetchAnime('all', 1).catch(() => []),
      ]);

      const newArticles: SEOArticle[] = [];

      // 4 Top Trending Movies
      const topMovies = moviesRes.slice(0, 4);
      topMovies.forEach((m) => {
        newArticles.push(synthesizeArticleForMedia(m, 'Movie Guides'));
      });

      // 3 Top Trending TV Series
      const topSeries = tvRes.slice(0, 3);
      topSeries.forEach((s) => {
        newArticles.push(synthesizeArticleForMedia(s, 'TV Series Guides'));
      });

      // 3 Top Trending Anime
      const topAnime = animeRes.slice(0, 3);
      topAnime.forEach((a) => {
        newArticles.push(synthesizeArticleForMedia(a, 'Anime Guides'));
      });

      if (newArticles.length === 0) {
        throw new Error('No trending titles returned from catalog API');
      }

      // Merge avoiding duplicate slugs
      const existingSlugs = new Set(this.customArticles.map((a) => a.slug));
      const addedArticles: SEOArticle[] = [];

      newArticles.forEach((art) => {
        if (!existingSlugs.has(art.slug)) {
          this.customArticles.unshift(art);
          addedArticles.push(art);
          existingSlugs.add(art.slug);
        }
      });

      this.settings.lastGeneratedDate = today;
      this.saveState();
      return addedArticles;
    } finally {
      this.isGenerating = false;
    }
  }

  public deleteArticle(idOrSlug: string): boolean {
    const beforeCount = this.customArticles.length;
    this.customArticles = this.customArticles.filter(
      (a) => a.id !== idOrSlug && a.slug !== idOrSlug
    );
    if (this.customArticles.length !== beforeCount) {
      this.saveState();
      return true;
    }
    return false;
  }

  public clearGeneratedArticles(): void {
    this.customArticles = [];
    this.settings.lastGeneratedDate = null;
    this.saveState();
  }

  public getStats() {
    const all = this.getAllArticles();
    const generated = this.customArticles;
    const today = new Date().toISOString().split('T')[0];

    const totalKeywords = all.reduce((sum, a) => sum + (a.keywords?.length || 0), 0);

    const categoriesCount = {
      movies: all.filter((a) => a.category === 'Movie Guides').length,
      series: all.filter((a) => a.category === 'TV Series Guides').length,
      anime: all.filter((a) => a.category === 'Anime Guides').length,
      curated: all.filter((a) => a.category === 'Curated Recommendations').length,
    };

    return {
      totalArticles: all.length,
      generatedCount: generated.length,
      curatedCount: SEO_ARTICLES.length,
      totalKeywordsTargeted: totalKeywords,
      lastGeneratedDate: this.settings.lastGeneratedDate,
      isGeneratedToday: this.settings.lastGeneratedDate === today,
      categoriesCount,
      estimatedMonthlySearchImpressions: all.length * 45000,
    };
  }
}

export const pseoEngine = new PSEOEngineService();
